Add constants for hide and show cursor
QubesOS/qubes-gui-common pull request #13
Opened 2022-02-25 17:10 UTC by locriacyber

2022-02-25 21:14 UTC, marmarek requested changes

2022-02-25 21:14 UTC, marmarek commented on include/qubes-gui-protocol.h
> +#define CURSOR_SHOW     0x1000
Is it necessary? `CURSOR_DEFAULT` (or some other specific one) should show the cursor, no?

2022-02-25 21:14 UTC, marmarek commented on include/qubes-gui-protocol.h
> +#define CURSOR_HIDE     0x2000
The whole 0x0000 - 0x00ff range is free for generic identifiers, you could use that as well (0x0001?).

2022-02-26 21:35 UTC, iacore commented on include/qubes-gui-protocol.h
> +#define CURSOR_SHOW     0x1000
Show and hide cursors (xfixes) are independent from setting the cursor shape (x11, no extension)

2022-02-26 21:38 UTC, locriacyber commented on include/qubes-gui-protocol.h
> +#define CURSOR_HIDE     0x2000
technically yes, but I want to reserve the last byte for actual cursor shapes, and second last byte for flags; we have 4 bytes to use

2022-03-05 03:09 UTC, locriacyber commented
Closed for being impossible to implement. See https://github.com/QubesOS/qubes-issues/issues/2676.

2022-03-05 03:09 UTC, closed without merging