Miscellaneous GUI protocol fixes
QubesOS/qubes-gui-common pull request #16
Opened 2022-03-31 03:32 UTC by DemiMarie

See individual commit messages for details.  The first commit adds a message for the daemon to tell the agent what version of the protocol it implements.  The second and third are purely documentation changes.

2022-07-05 21:09 UTC, DemiMarie commented
PipelineRetry

2022-07-08 00:57 UTC, marmarek requested changes
As discussed, the `msg_xconf` hack will not be necessary, and actually wouldn't be effective without any gui-daemon change. So, please adjust for newer design (probably reducing the change to just a comment about initial version info sent as `uint32_t`).

2022-07-08 04:55 UTC, DemiMarie commented
> As discussed, the `msg_xconf` hack will not be necessary, and actually wouldn't be effective without any gui-daemon change. So, please adjust for newer design (probably reducing the change to just a comment about initial version info sent as `uint32_t`).

I did the adjustment, but I kept the two older commits (both comment-only) and added a `struct msg_version`.

2022-07-08 10:09 UTC, marmarek approved these changes

2022-10-12 02:03 UTC, merged